#!/bin/bash -eu

if [ -d "/tmp/artifacts/.cabal" ]; then
  mv /tmp/artifacts/.cabal/* ~/.cabal
  cd ~/.cabal/packages/stackage
  gzip -d <00-index.tar.gz >00-index.tar
fi
if [ -d "/tmp/artifacts/.ghc" ]; then
  mv /tmp/artifacts/.ghc ~
  ghc-pkg recache --user
fi

cd /tmp/src

function marker {
  [ -f ".sti/markers/$1" ]
}

function hook {
  if [ -f ".sti/hooks/$1" ]; then
    echo "running hook $1 ..."
    .sti/hooks/$1
  fi
}

#cabal stuff
if marker cabal_update || [ ! -d ~/.cabal/packages ]; then
  marker cabal_update && echo "marker: cabal_update ..."
  cabal update
fi
if marker sequential; then
  echo "marker: sequential"
  sed -i "s|jobs| -- jobs|" ~/.cabal/config
fi

hook before_build

if marker run_tests; then
  echo "marker: run_tests ..."
  cabal install --enable-tests --only-dependencies
  cabal test
fi
if marker cabal_flags; then
  flags=$(cat .sti/markers/cabal_flags)
  echo "marker: cabal_flags: $flags"
  cabal install -f"$flags"
else
  cabal install
fi

hook after_build

rm -r /tmp/*