#!/bin/bash -eu

cd ~
shopt -s extglob
exec tar -c .@(cabal|ghc) \
--exclude=".cabal/config" \
--exclude=".cabal/bin/server" \
--exclude=".cabal/packages/*/00-index.cache" \
--exclude=".cabal/packages/*/00-index.tar" \
--exclude=".ghc/*/package.conf.d/package.cache"