#!/bin/bash -eu

case "$1" in
  network)
    name="Haskell"
	description="GHC and cabal-install"
    ;;
  yesod)
    name="Yesod"
	description="GHC, Yesod and Esqueleto"
    ;;
  scotty)
    name="Scotty"
	description="GHC and Scotty"
    ;;
  snap)
    name="Snap"
	description="GHC and Snap"
    ;;
  mflow)
    name="MFlow"
	description="GHC and MFlow"
    ;;
  happstack)
    name="Happstack"
	description="GHC and Happstack"
    ;;
  *)
    echo "Unknown framework $1" >&2
    exit 1
esac

docker build -t ghc-temp --build-arg framework="$1" image

docker build -t accursoft/ghc-$1 - <<EOF
FROM ghc-temp
MAINTAINER Gideon Sireling <code@accursoft.com>
LABEL io.openshift.s2i.scripts-url="image://opt/s2i" \
      io.k8s.display-name="$name" \
      io.k8s.description="$description" \
      io.openshift.tags="haskell,ghc,$1,$(docker run --rm ghc-temp | tr '\n' ',')builder" \
      io.openshift.expose-services="8080:http"
EOF
docker tag accursoft/ghc-$1 accursoft/ghc-$1:$(docker run --rm ghc-temp ghc --numeric-version)

docker rmi ghc-temp