FROM fedora
MAINTAINER Gideon Sireling <gideon@accursoft.com>

#https://github.com/haskell/cabal/issues/1883
#https://github.com/dotcloud/docker/issues/2424
ENV LANG en_US.UTF-8

ADD ghc.sh /tmp/
RUN /tmp/ghc.sh

ADD cabal.sh /tmp/
RUN /tmp/cabal.sh

ADD framework.sh /tmp/
RUN /tmp/framework.sh <framework>

RUN rm -rf /tmp/*
