FROM debian:wheezy
MAINTAINER Gideon Sireling <gideon@accursoft.com>

#https://github.com/haskell/cabal/issues/1883
#https://github.com/dotcloud/docker/issues/2424
ENV LANG en_US.UTF-8

COPY ghc.sh /tmp/
RUN /tmp/ghc.sh

COPY cabal.sh /tmp/
RUN /tmp/cabal.sh

COPY framework.sh /tmp/
RUN /tmp/framework.sh <framework>

RUN rm -rf /tmp/*
