#!/bin/bash -eu

s2i="s2i build --rm --incremental . accursoft/ghc-network test"

function check {
  echo "  * Testing $1 ..."
  $s2i
  docker run --name test -d -p 8080:8080 test >/dev/null
  sleep 0.01
  if curl -sS localhost:8080 | grep -q $2; then
    docker rm -f test >/dev/null
    return
  fi
  echo "  * $1 FAILED"
  exit 1
}

function check_build {
  echo "  * Testing $1 ..."
  $s2i |& tee ../build.log
  grep -q "$2" ../build.log && return
  echo "  * $1 FAILED"
  exit 1
}

#build image
cd image
./build network

#create app
cd ..
rm -rf server
curl -s https://bitbucket.org/accursoft/haskell-cloud-template/get/default.tar.bz2 | tar xj
mv accursoft-haskell-cloud-template-* server
cd server
rm .s2i/hooks/* .s2i/markers/*
check "create app" "Welcome"

#cabal flags
cp Main.hs test.hs
sed -i 's/handle response/handle "Greetings"/' test.hs
echo "Flag A" >>server.cabal
sed -i 's/main-is: *Main.hs/if flag(a) {main-is:Main.hs} else {main-is:test.hs}/' server.cabal
echo "b" >.s2i/markers/cabal_flags
check "enable flags" "Welcome"
echo "-a" >>.s2i/markers/cabal_flags
check "unset flag" "Greetings"
rm .s2i/markers/cabal_flags

#run_tests
touch .s2i/markers/run_tests
echo "main = return ()" >test.hs
echo "test-suite test
  type:exitcode-stdio-1.0
  main-is:test.hs
  build-depends:groups" >>server.cabal
  #check that test dependencies are installed
check "run_tests" "Welcome"
rm .s2i/markers/run_tests

#pre_build hook
echo "sed -i 's/Welcome/Greetings/' response" >.s2i/hooks/pre_build
chmod +x .s2i/hooks/pre_build
check "pre_build hook" "Greetings"
rm .s2i/hooks/pre_build

#preserve installed packages
sed -i 's/network/network,groups/' server.cabal
check_build "use previously installed package" "server"
if grep -q "groups2" ../build.log; then
  echo "  * package groups from earlier build was not reused - FAILED"
  exit 1
fi

#sequential build
touch .s2i/markers/sequential
check_build "sequential build" "Compiling"
rm .s2i/markers/sequential

#cabal_update
touch .s2i/markers/cabal_update
check_build "cabal_update" "Downloading the latest package list"
rm .s2i/markers/cabal_update

#logs
touch .s2i/markers/logs
check_build "logs" "Compiling"
rm .s2i/markers/logs

#pre_run hook
echo "sed -i 's/Welcome/Greetings/' ~/.cabal/share/*/server-*/response" >.s2i/hooks/pre_run
chmod +x .s2i/hooks/pre_run
check "pre_run hook" "Greetings"
rm .s2i/hooks/pre_run

echo "PASSED"

#clear up
cd ..
rm -r server build.log
docker rmi test >/dev/null

docker run --rm accursoft/ghc-network cat /opt/s2i/provides