#!/bin/sh -eu

cd ~
exec tar -c \
--exclude=".cabal/config" \
--exclude=".cabal/packages/*/root.json" \
--exclude=".cabal/share/*/server-*" \
--exclude=".cabal/bin/server" \
$(ls -d .cabal .ghc 2>/dev/null)