#!/bin/bash -eu

if [ -d "/tmp/artifacts/.cabal" ]; then
  mv /tmp/artifacts/.cabal/* ~/.cabal
  cd ~/.cabal/packages/*
  gzip -dk 00-index.tar.gz
fi
if [ -d "/tmp/artifacts/.ghc" ]; then
  mv /tmp/artifacts/.ghc ~
  ghc-pkg recache --user
fi

cd /tmp/src

function marker {
  if [ -f ".sti/markers/$1" ]; then
    echo "marker: $1"
  else
    return 1
  fi
}

function hook {
  if [ -f ".sti/hooks/$1" ]; then
    echo "running hook $1 ..."
    .sti/hooks/$1
  fi
}

#cabal stuff
if marker cabal_update || [ ! -d ~/.cabal/packages ]; then
  cabal update
fi
if marker sequential; then
  sed -i "s|jobs| -- jobs|" ~/.cabal/config
else
  echo "$(nproc) CPUs available for parallel builds"
fi

hook pre_build

if marker run_tests; then
  cabal install --enable-tests --only-dependencies
  cabal test
fi
if marker cabal_flags; then
  flags=$(cat .sti/markers/cabal_flags)
  echo "$flags"
  cabal install -f"$flags"
else
  cabal install
fi
if marker logs; then
  cd ~/.cabal/logs
  tail -n+1 $(ls -I build.log -rt)
  cd - >/dev/null
fi

hook post_build

if [ -f ".sti/hooks/pre_run" ]; then
  mkdir ~/.sti
  mv .sti/hooks/pre_run ~/.sti
  echo "installed pre_run hook"
fi

#clean up
cd ~
rm -rf /tmp/* \
  .cabal/packages/*/00-index.cache \
  .cabal/packages/*/00-index.tar \
  .cabal/logs \
  .ghc/*/package.conf.d/package.cache