FROM debian:wheezy
MAINTAINER Gideon Sireling <gideon@accursoft.com>

COPY ghc.sh /tmp/
RUN /tmp/ghc.sh

COPY cabal.sh /tmp/
RUN /tmp/cabal.sh

COPY framework.sh /tmp/
RUN /tmp/framework.sh <framework>

RUN rm -rf /tmp/*

RUN useradd -r -m -k /dev/null -s /usr/sbin/nologin haskell
USER haskell

#generate default cabal config
RUN cabal get

ENV PORT 8080
EXPOSE $PORT
ENV PATH $PATH:/home/haskell/.cabal/bin

COPY sti /opt/sti/
ENV STI_SCRIPTS_URL image://opt/sti
CMD ["/opt/sti/sti-helper"]